//@ui5-bundle sap/ushell/components/shell/Search/Component-preload.js
// Copyright (c) 2009-2025 SAP SE, All Rights Reserved
sap.ui.predefine("sap/ushell/components/shell/Search/Component", ["sap/ui/core/EventBus","sap/ushell/components/shell/Search/ESearch","sap/ui/core/UIComponent","sap/ui/core/Component","sap/ushell/utils","sap/base/util/ObjectPath","sap/ushell/Container"],function(e,a,t,n,s,l,r){"use strict";return t.extend("sap.ushell.components.shell.Search.Component",{metadata:{manifest:"json",library:"sap.ushell"},createContent:function(){var t=this;var o=l.get("sap-ushell-config.services.SearchCEP")!==undefined;var i=r.getRendererInternal("fiori2").getShellController(),c=i.getView(),h=(c.getViewData()?c.getViewData().config:{})||{};var u=h.enableSearch!==false;if(!u){e.getInstance().publish("shell","searchCompLoaded",{delay:0});return}r.getFLPPlatform().then(function(l){if(l==="MYHOME"||l==="cFLP"&&o===true){n.create({manifest:false,name:"sap.ushell.components.shell.SearchCEP"})}else{a.createContent(t);e.getInstance().publish("shell","searchCompLoaded",{delay:0})}s.setPerformanceMark("FLP -- search component is loaded")})},exit:function(){a.exit()}})});
// Copyright (c) 2009-2025 SAP SE, All Rights Reserved
sap.ui.predefine("sap/ushell/components/shell/Search/ESearch", ["sap/ui/core/Element","sap/ui/core/Lib","sap/ushell/resources","sap/ui/core/IconPool","sap/ui/core/routing/HashChanger","sap/ui/thirdparty/jquery","sap/ushell/renderer/search/util","sap/ushell/Container","sap/ushell/Config"],function(e,a,n,r,t,jQuery,s,i,l){"use strict";var h=false;var o=function(e){if(!e._searchShellHelperPromise){e._searchShellHelperPromise=new Promise(function(e){a.load("sap.esh.search.ui").then(function(){sap.ui.require(["sap/esh/search/ui/SearchShellHelperAndModuleLoader","sap/esh/search/ui/SearchShellHelper"],function(a,n){n.init();e(n)})})})}return e._searchShellHelperPromise};function u(u){h=true;if(l.last("/core/shellBar/enabled")){o(u).then(function(e){e.init()});e.getElementById("shell-header").attachSearchButtonPress(e=>{o(u).then(function(a){a.onShellSearchButtonPressed(e)})})}var c={id:"sf",tooltip:"{i18n>openSearchBtn}",text:"{i18n>searchBtn}",ariaLabel:"{i18n>openSearchBtn}",icon:r.getIconURI("search"),visible:true,press:function(e){o(u).then(function(a){a.onShellSearchButtonPressed(e)})}};var d=i.getRendererInternal("fiori2").addHeaderEndItem("sap.ushell.ui.shell.ShellHeadItem",c,true,false);d.data("help-id","shellHeader-search",true);if(s.isSearchFieldExpandedByDefault()){d.setVisible(false)}d.setModel(n.i18nModel,"i18n");if(s.isSearchFieldExpandedByDefault()){o(u).then(function(e){if(e.expandSearch){e.expandSearch()}else{d.setVisible(true)}})}u.oHashChanger=t.getInstance();u.oHashChanger.attachEvent("shellHashChanged",function(e){var n=e.mParameters;setTimeout(function(){a.load("sap.esh.search.ui").then(function(){sap.ui.require(["sap/esh/search/ui/HashChangeHandler"],function(e){e.handle(n)})})},6e3)});d.addEventDelegate({onAfterRendering:function(){jQuery("#sf").attr("aria-pressed",false)}})}function c(){if(h){i.getRendererInternal("fiori2").hideHeaderEndItem("sf");var a=e.getElementById("sf");if(a){a.destroy()}}}return{createContent:u,exit:c}});
sap.ui.require.preload({
	"sap/ushell/components/shell/Search/manifest.json":'{"_version":"1.34.0","sap.app":{"id":"sap.ushell.components.shell.Search","applicationVersion":{"version":"1.136.1"},"i18n":{"bundleUrl":"../../../renderer/resources/resources.properties","fallbackLocale":"en"},"type":"component","title":"","resources":"resources.json"},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"dependencies":{"minUI5Version":"1.92","libs":{"sap.m":{},"sap.ui.layout":{}}},"models":{},"contentDensities":{"compact":true,"cozy":true}}}'
});
//# sourceMappingURL=Component-preload.js.map
